version: '3.9'

services:
  database:
    image: jacksagliano99/database:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    image: jacksagliano99/backend:latest
    container_name: backend-server
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "3000:3000"
    networks:
      - backend_network

  frontend:
    image: jacksagliano99/frontend:latest
    container_name: frontend-server
    depends_on:
      - backend
    ports:
      - "4200:80" 
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
